"""initial_schema

Revision ID: edeb0279b7be
Revises: 
Create Date: 2026-04-19 17:10:18.281044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edeb0279b7be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovered_domains_domain'), 'discovered_domains', ['domain'], unique=True)
    op.create_index(op.f('ix_discovered_domains_id'), 'discovered_domains', ['id'], unique=False)
    op.create_table('discovered_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['discovered_domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'url', name='uq_discovered_urls_domain_url')
    )
    op.create_index(op.f('ix_discovered_urls_domain_id'), 'discovered_urls', ['domain_id'], unique=False)
    op.create_index(op.f('ix_discovered_urls_id'), 'discovered_urls', ['id'], unique=False)
    op.drop_constraint('corrections_labeler_id_fkey', 'corrections', type_='foreignkey')
    op.create_foreign_key(None, 'corrections', 'users', ['labeler_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'corrections', type_='foreignkey')
    op.create_foreign_key('corrections_labeler_id_fkey', 'corrections', 'users', ['labeler_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_discovered_urls_id'), table_name='discovered_urls')
    op.drop_index(op.f('ix_discovered_urls_domain_id'), table_name='discovered_urls')
    op.drop_table('discovered_urls')
    op.drop_index(op.f('ix_discovered_domains_id'), table_name='discovered_domains')
    op.drop_index(op.f('ix_discovered_domains_domain'), table_name='discovered_domains')
    op.drop_table('discovered_domains')
    # ### end Alembic commands ###
